@echo off
REM 批量创建 CNAME 文件
echo babyformulatool.org > "babyformulatool\CNAME"
echo bedtimecycle.com > "bedtimecycle.com\CNAME"
echo bmitool.org > "bmitool\CNAME"
echo bodycompcheck.org > "bodycompcheck\CNAME"
echo budgetcalctool.org > "budgetcalctool.org\CNAME"
echo caffeinecheck.com > "caffeinecheck.com\CNAME"
echo catcalorietool.org > "catcalorietool\CNAME"
echo coveragecheckr.com > "coveragecheckr.com\CNAME"
echo dailyprotein.net > "dailyprotein.net\CNAME"
echo debtbreakdown.com > "debtbreakdown.com\CNAME"
echo dogcalorietool.org > "dogcalorietool\CNAME"
echo duedatetool.org > "duedatetool.org\CNAME"
echo electricbillcheck.com > "electricbillcheck.com\CNAME"
echo equityunlock.org > "equityunlock.org\CNAME"
echo fastingtool.org > "fastingtool\CNAME"
echo hydrationcalc.net > "hydrationcalc.net\CNAME"
echo insurancecalctool.org > "insurancecalctool\CNAME"
echo investcomparetool.org > "investcomparetool\CNAME"
echo loancalctool.org > "loancalctool\CNAME"
echo mortgagecalctool.org > "mortgagecalctool\CNAME"
echo ovulationtracktool.org > "ovulationtracktool\CNAME"
echo petcalcentral.org > "petcalcentral\CNAME"
echo quickloantool.org > "quickloantool\CNAME"
echo recipeportions.com > "recipeportions.com\CNAME"
echo refinancecalctool.org > "refinancecalctool\CNAME"
echo taxcalctool.org > "taxcalctool\CNAME"
echo tiresizehub.org > "tiresizehub\CNAME"
echo travelbudgetpro.org > "travelbudgetpro.org\CNAME"
echo wattwise.org > "wattwise.org\CNAME"
echo weddingbudgetly.com > "weddingbudgetly.com\CNAME"
echo CNAME 文件创建完成！
pause